# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- develop

pr:
- master

variables:
  developmentBranchName: 'master' 

resources:
  repositories:
    - repository: templates
      type: git
      name: 'TestService/CommonYml'

stages:
    - stage: 'Build'
      displayName: 'Build the $(apiService)'
      jobs:
          - job: 'Build'
            displayName: 'Build job'
            pool:
              vmImage: 'ubuntu-latest' 
           
              
            steps:  
            - template: 'CommonBuildPipeline_dev.yml@templates'

